name: examples
on:
  - push
  - pull_request
jobs:
  check-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i shelljs chalk
      - run: npm run check-examples
